version: '3'
services:
  app:
    build: SpeurzoekersApp/.
    ports:
    - "5000:80"
    networks:
      - default
    
  service:
    build: SpeurzoekersService/.
    ports:
    - "5001:80"
    networks:
      - default

networks:
  default: